version: "3.8"

services:
  postgres-test:
    image: postgres:15
    container_name: taskflow_test_db
    ports:
      - "5433:5432" # expose on a non-default port to avoid conflict with local PG
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: taskflow_test
    volumes:
      - pg_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test_user"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pg_test_data:
