version: "3.8"

services:
  postgres-test:
    image: postgres:15
    container_name: "${POSTGRES_DB}_db"
    ports:
      - "5432:5432" # expose on a non-default port to avoid conflict with local PG
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test_user"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pg_test_data:
